### ISSUE TITLE
v1.3.4 fails to run on 8086 CPU

### ISSUE THREAD

**Issue by bttrx** [FDOS/fdisk#13]
To fix this:
1. Remove `-1` from [CFLAGS](https://github.com/FDOS/fdisk/blob/52944968a2f220d4efe236d1692819019a349b10/SOURCE/FDISK/MAKEFILE#L14).
2. Add options `--best --8086` to [UPX](https://github.com/FDOS/fdisk/blob/52944968a2f220d4efe236d1692819019a349b10/SOURCE/FDISK/MAKEFILE#L39)

**Comment by boeckmann** [comment]
Fixed by https://github.com/FDOS/fdisk/commit/44df64198de41bd5adcd4f1180b6d936d6cb48c5.
