### ISSUE TITLE
build fails because of DPMI conflicts between NASM and Borland make

### ISSUE THREAD

**Issue by boeckmann** [FDOS/fdisk#15]
After reordering my PATH variable I noticed that the CWSDPMI build of NASM does not work anymore when invoked by Borland make.

Seems there are different versions of the make utility: A 16-bit protected mode version shipped with Turbo C++ 3.0 and Borland C++ 3.1 and a real mode version shipped with Borland Pascal 7.

If using the real mode make from Pascal the build runs perfectly, but NASM fails to launch if invoked by 16-bit protected mode version.

My guess is that this is "only" a problem under DosBox and DOS without a proper 16/32 bit DPMI host loaded prior to building the software. It should run fine under Win 3.1 - Win ME.

I am not sure how to solve this for all build tool combinations but document it here if someone has the same problem.

**Comment by andrewbird** [comment]
I wonder if it would be best to switch to GNU make for all compilers. It has the advantage that it works without modification on Linux, DOS and Windows.

**Comment by boeckmann** [comment]
I can try to write a toolchain agnostic makefile for GNU make, as a first step towards supporting IA16-GCC as a compiler.

**Comment by boeckmann** [comment]
This is obolete (Borland support removed).
