### ISSUE TITLE
Incorrect rounding causes overlapped partitions

### ISSUE THREAD

**Issue by PerditionC** [FDOS/fdisk#2]
See https://www.bttr-software.de/forum/forum_entry.php?id=17463

Apparently in rounding to cylinder boundary, fdisk rounds down when it should round up.  Additionally, it should verify it is not creating overlapping partitions, especially if some were created by other partitioning software.

**Comment by boeckmann** [comment]
It in fact fails at the most simple use case:

Creating a partition spawning the whole disk and opening with FDISK a second time (make it active so partition table gets written) results in the end cylinder getting increased by one. As a result the partition exceeds the disk end by one cylinder.

I could at least configm it for the following disk geometry: 240 MB, CHS 489/16/63, Total sectors 492912

I am not yet sure if it is the same bug as mentioned in the issue title, but I will investigate it as soon as I finished testing the Watcom port.

**Comment by boeckmann** [comment]
There were multiple calculation and rounding errors, which are hopefully all fixed by v1.3.5, see [DOC/FDISK/CHANGES.md](https://github.com/FDOS/fdisk/blob/8cf8f0a5cf8c5d0e53f1e1d740f221878582cdab/DOC/FDISK/CHANGES.md)

**Comment by boeckmann** [comment]
Closing this one. If new overlapping errors occur I will open new, more specific issues for it.
