### ISSUE TITLE
Is the Borland build still relevant?

### ISSUE THREAD

**Issue by mateuszviste** [FDOS/fdisk#30]
FDISK comes with Makefiles for OpenWatcom and Borland.

Is there a reason to look over two builds? Sticking to one (preferably OW?) would make it less of a nuisance for developers to take care of the code. Not that I am particularly concerned of course. It's truly an open question.

**Comment by boeckmann** [comment]
Good question. In my opinion, because the Borland tools are proprietary stuff, support could be dropped. But I do not want to decide this by myself. There is one advantage in supporting multiple compilers: chances to catch errors are higher. Perhaps @PerditionC  and the others may give their opinion here.

**Comment by andrewbird** [comment]
I like to be able to build FreeDOS software with Watcom and Gcc-ia16 as both have cross compiler variants available for Linux and so can be added to Github's CI for a Linux based build. One thing though, I don't see any advantage in having  builds that use each compiler's specific make, I'd just prefer to standardise on Gnu make for all builds.
That said, I don't have much time at the moment for FreeDOS or Dosemu, so whomever does the work gets to choose, and for the moment, that's not me. :smile:

**Comment by boeckmann** [comment]
I would like to be able to build it under DosBox with only OpenWatcom installed. Therefore I prefer to having an OpenWatcom Makefile. But nothing speaks against an additional GNU Makefile :-)

Regarding a GCC-IA16 port, there is already #23. Will be a big task and I am not sure it will happen anytime soon. But we should keep it in mind when adding new code, namely try to not introduce more vendor specific code.

**Comment by boeckmann** [comment]
In the light of having an additional compiler in the future I think it is ok to break with the Borland support.

**Comment by boeckmann** [comment]
Borland support is removed, now that FDISK compiles with IA16-GCC, we have a second open source compiler. This should be enough.
