### ISSUE TITLE
Configurable name (Free FDISK vs FreeDOS FDISK)

### ISSUE THREAD

**Issue by mateuszviste** [FDOS/fdisk#44]
FDISK can be built as two different names: Free FDISK or FreeDOS FDISK. All the rest is strictly identical, only the names change.

Is this really necessary? I mean, it's a complication for the build and for translations, while it does not provide any functional difference. Maybe would it be possible to select one of the names and stick to it?
FDISK
Free FDISK
FreeDOS FDISK

My preference goes to just "FDISK", but if there is a risk of confusion with MS FDISK, then Free FDISK would be my second choice.

**Comment by boeckmann** [comment]
Thats a good question. I took that in because somtimes it gets called FreeDOS FDISK, and somtimes Free FDISK. I was not sure about it and wanted to make everyone happy :-) But now I think we can throw it out and stick with Free FDISK.

**Comment by mateuszviste** [comment]
on a semi-related note: the credits on the main screen. "GNU GPL, Copyright Brian Reifsnyder and the FreeDOS Community".

It looks a little bit ugly IMO, too much data on screen. I'd suggest removing it entirely and leaving only the program's name and subtitle "Fixed Disk Setup Program". The licensing, copyrights and credits are all already in the documentation. Besides I am not sure if "FreeDOS Community" legally means anything, really.

Interestingly, these credits disappear after going to a submenu and getting back to main menu. That's a few IFs that could be removed and less translation strings to process...

**Comment by boeckmann** [comment]
I agree. I considered it by myself a few months ago, but at that time left it in to give the original author his credentials. Now I think it is ok to have it in the documentation.

**Comment by boeckmann** [comment]
I'll ask Jim he is OK with it to call it just Free FDISK.

**Comment by PerditionC** [comment]
Personally, I would drop the Free and just call it FDisk.  "FreeDOS" is implied by being included, so FreeDOS FDisk as a name doesn't seem to be needed.  That said, any are fine.

**Comment by boeckmann** [comment]
I talked to Jim, and we settled to the "Free FDISK" name, to differentiate it from other FDISK implementations.
