### ISSUE TITLE
Allow zero-sized strings in translations?

### ISSUE THREAD

**Issue by boeckmann** [FDOS/fdisk#45]
If I understand correct, a zero-sized string is used as a termination marker in the compiled translation files. In the source translation files, there are lines like:
```
3.0:\t
```
I guess to prevent zero-sized strings? While doing german translation one of my multi-line strings was shorter than the original one, and I had a line like
```
3.5:
```
in the file, which totally broke things.

Perhaps one could reconsider to use $FFFF instead of 0 as a table termination marker? Would allow empty strings. I am also not sure if its wise to strip the trailing spaces. Please correct me if I understood it wrong.

**Comment by boeckmann** [comment]
@mateuszviste Seems I was not completely correct. parseline of tlumacz returns NULL if the string length is zero. Does it have to be? Because the length written in the binary file is at least 1 because of the trailing '\0'.

**Comment by mateuszviste** [comment]
I am not sure I understand the problem. Storing empty strings just for the sake of storing them does not sound efficient. Whenever a string does not exist in the ressource file, the svarlang lib actually returns an empty string (and this is meant as a safety, so applications do not crash if they unexpectedly get a NULL). Can you please elaborate on the exact issue you noticed?

**Comment by mateuszviste** [comment]
about the \t trick: it is for the fdisk's help screen routine, so it can differentiate "string does not exist" (empty) and "this is a valid line that needs to be printed". With this the routine does not have to remember all lines that need to be printed, but just iterate over the entire category 0 and print a line whenever it gets something. the \t being a whitespace, it ends up being an empty line.

**Comment by boeckmann** [comment]
This: https://github.com/FDOS/fdisk/blob/6cd0225e62248fde36b503815fed3698a46dce8c/SOURCE/FDISK/SVARLANG/tlumacz.c#L95
leads to termination if a line like
```
3.0:
```
is encountered, and the rest of the translation file is ignored, because of https://github.com/FDOS/fdisk/blob/6cd0225e62248fde36b503815fed3698a46dce8c/SOURCE/FDISK/SVARLANG/tlumacz.c#L165C2-L165C2

If I interpret it correctly.

**Comment by mateuszviste** [comment]
> I am also not sure if its wise to strip the trailing spaces

Well, many editors strip trailing spaces automatically. I consider allowing for such trailing spaces to be generally a nuisance, because either the files end up with trailing space garbage that the translator did not notice, or the file will break at some point when someone edits it with a space-trimming editor.

I think that translations should not contain any such formatting, ie. neither trailing nor leading spaces. For instance the "do-you-want-FAT32" screen is not very good now as it contains lots of trailing spaces, which is both a waste of storage and a trouble for translators, who will be forced to count each space to make sure their translations appear more or less like the original...

**Comment by mateuszviste** [comment]
> This:
> 
> https://github.com/FDOS/fdisk/blob/6cd0225e62248fde36b503815fed3698a46dce8c/SOURCE/FDISK/SVARLANG/tlumacz.c#L95
> 
> leads to termination if a line like
> 
> ```
> 3.0:
> ```
> 
> is encountered, and the rest of the translation file is ignored, because of https://github.com/FDOS/fdisk/blob/6cd0225e62248fde36b503815fed3698a46dce8c/SOURCE/FDISK/SVARLANG/tlumacz.c#L165C2-L165C2
> 
> If I interpret it correctly.

Ah, so you mean "allowing to store zero-len strings in the CATS-style source". I thought you were referring to the LNG storage and that's what I answered about.
You are correct, a line like "1.0:" is considered to be malformed. This was meant to be a way to detect errors introduced by translators, but perhaps indeed there are legitimate cases for such entries.
In the situation that you mention, wouldn't it make sense to store the entire phrase in one piece in the CATS-style translation, including \n markers in it? I'm honestly not sure what's the best approach.

**Comment by mateuszviste** [comment]
maybe a compromise would be to tolerate "malformed" lines and only emit a warning, but continue to parse the file until the end?

**Comment by boeckmann** [comment]
Yes, I would strongly prefer storing it as one string. Then the text can span a different number of lines between translations.

I pushed a quick interim fix.

**Comment by boeckmann** [comment]
Please see https://github.com/FDOS/fdisk/commit/41a39d083887c8a6ce6efb5a8b54de16ce271d5d. That should fix it.

**Comment by mateuszviste** [comment]
I was just looking at it - it is precisely what I was thinking about. Any chance you could push this fix upstream as well? :-)

**Comment by boeckmann** [comment]
> I was just looking at it - it is precisely what I was thinking about. Any chance you could push this fix upstream as well? :-)

Sure, will do it tomorrow, have to get some sleep. Is upstream your SVN?

**Comment by mateuszviste** [comment]
yes, it is stored in svardos/svarlang.lib/trunk
