### ISSUE TITLE
Refactor svarlang

### ISSUE THREAD

**Issue by boeckmann** [FDOS/fdisk#60]
@mateuszviste New issue to not pollute the french language issue.

**Comment by boeckmann** [comment]
So, I had some thoughts about svarlang in general: What I noticed is that the linear search for the strings is becoming noticeably slow, at least on a 8086 and for the number of strings FDISK contains.

I already mentioned that I would like to be able to do a binary search on the strings to speed it up. That would mean that some form of search table must exist.

This search table can be build either at runtime or at compilation time of the .LNG file. The table is simply an array of (string-id, string-ptr), where the array is sorted by string-id.

It is no problem to build this at runtime. But this would be a space and time waster. It is a time waster, because, obviously the table is built on every programm launch. It is a space waster because in addition to the language data itself the table consumes 4*n bytes, with n being the number of strings (at least if there is no extra work going on in compacting the contents of svarlang_mem).

I would therefore prefer to alter the layout of the .LNG file, so that the above mentioned table followed by the strings is stored for the individual languages instead of a linked list. It would be equally space-efficient, but enables a more speedy lookup.

@mateuszviste I don't know if you are generally interested in it, but I would help implementing this for svarlang in general. Otherwise I will at least try to incorporate it into the FDISK source in some kind.

**Comment by boeckmann** [comment]
Further, a `svarlang_len(int strid)` would make sense, because this information is basically existant. It will be faster than the default strlen, which must search for the binary zero.

**Comment by mateuszviste** [comment]
> I would therefore prefer to alter the layout of the .LNG file, so that the above mentioned table followed by the strings is stored for the individual languages instead of a linked list. It would be equally space-efficient, but enables a more speedy lookup.

So the strings would no longer be prefixed by their id and length, instead there would be a table with id,offset pairs in front of the language block. That would be indeed equally space efficient as today. question is - would it be really faster? If this table would be looked up sequentially, then the performances would be the same as today, but if some dichotomy is applied when scanning the table, then indeed performances could be greatly improved. To apply a dichotomic search the lookup algorithm would need to know the amount of items in the table, so this information would have to be added as well (but that's still no waste because we can drop the empty list-terminator that is currently appended to the language block, so the new format would be effectively more compact than the current one, by a byte or two).

> I don't know if you are generally interested in it

I am much interested in any SvarLANG / SvarDOS improvements, and I am very happy to see you playing with it. :-)

**Comment by boeckmann** [comment]
Yes, the number of elements must be known. The table should be sorted to benefit from a faster look up. If it is sorted, a search like this can be performed:

https://github.com/boeckmann/asm6502/blob/ba04564c7f6c49231e4211276a6feb1facfb3df5/src/asm6502.c#L1948

I know this under the term binary search. I am not known to the term dichotomic search. But it probably means the same.

**Comment by boeckmann** [comment]
Regarding to the question, if it is faster: While programming the software linked above, I noticed that starting with 20-30 elements, the binary search started to outperform the linear search.

**Comment by mateuszviste** [comment]
I did not know the term "binary search" but a wiki lookup confirms we indeed talk about the same thing:
https://en.wikipedia.org/wiki/Dichotomic_search

> I noticed that starting with 20-30 elements, the binary search started to outperform the linear search.

Awesome!

**Comment by mateuszviste** [comment]
I've implemented a first attempt of svarlang_autoload_exepath(), but got into an issue I failed to foresee: the program's environment is necessarily accessible through a far pointer, which means that using the filename ("exepath") of the program requires to pass a far pointer to svarlang_load(). And that will break on memory models that default to near pointers. Not sure what the solution would be. Perhaps copying the exepath to a stack-based buffer is the sanest thing to do after all.

**Comment by boeckmann** [comment]
Ok, I figured out you obviously want to relieve the programmer from passing argv[0] :-)

- On Watcom there is the non-standard __argv defined in stdlib, which could be used. I16-GCC probably has something similar. If not we can provide TKchia with a feature request. 
- Otherwise, copying would be the best option I guess (either by using fstrcpy or doing it by hand with far pointers).
- Declaring svarlang_load( char __far *fn) seems ugly but is possible, might pull in some additional far versions of library functions, whatever is used in svarlang_load. This might not be desirable.

**Comment by mateuszviste** [comment]
> Ok, I figured out you obviously want to relieve the programmer from passing argv[0] :-)

There is that, yes, but also the fact that I am not 100% sure where argv[0] comes from. Typically, do we have the guarantee that when launching an executable from %PATH% argv[0] it will contain the actual path and not only "FDISK.EXE"? If yes (I truly don't know) then relying on __argv might be the best idea.

>     * On Watcom there is the non-standard __argv defined in stdlib, which could be used. I16-GCC probably has something similar. If not we can provide TKchia with a feature request.

Agreed.

>     * Otherwise, copying would be the best option I guess (either by using fstrcpy or doing it by hand with far pointers).

The initial idea was to avoid the need of an extra buffer, but I realize it might not be as easy as I hoped.

>     * Declaring svarlang_load( char __far *fn) seems ugly but is possible, might pull in some additional far versions of library functions, whatever is used in svarlang_load. This might not be desirable.

More importantly it would break on the fopen() call.

**Comment by boeckmann** [comment]
Do you want svarlang be portable to operating systems other than DOS, or keeping it DOS-only? That would heavily influence the things one can rely on.

> There is that, yes, but also the fact that I am not 100% sure where argv[0] comes from. Typically, do we have the guarantee that when launching an executable from %PATH% argv[0] it will contain the actual path and not only "FDISK.EXE"? If yes (I truly don't know) then relying on __argv might be the best idea.

No, generally that can not be relied on. At least if strictly following the ANSI C standard, which states that the program name does not even have to be in argv[0]:

> If the value of argc is greater than zero. the string pointed to by argv [0] represents the program name. argv [0] [0] shall be the null character if the program name is not available trom the host environment. -- ANSII/SO9899-1990

So basically, there is no standardized way of doing it. But, at least under DOS, Watcom reads its argv argument from the environment pointed to by the PSP. That is under FreeDOS guaranteed to contain the full path (should be safe to assume it is following MS-DOS behaviour here):

https://github.com/boeckmann/kernel/blob/29ccb6e45414a8a18346a97fdb0f35ebd6fb4025/kernel/task.c#L200

The Watcom startup code checks for DOS version 3 before reading the file name (perhaps because the environment block is not even there in DOS <3?!?). So if you want it to be running on DOS <3 that would be some extra work.

https://github.com/open-watcom/open-watcom-v2/blob/1a0e7d52808ecd423a08be8cfbeb2276e40b55ed/bld/clib/startup/a/cstrt086.asm#L336

I did a quick test with IA16-GCC. It seems to behave the same like Watcom. argv[0] contains an absolute path, even if I start it with a relative path. The `__argv` is also provided.

For the start, I would use the __argv thing guarded by a `#if defined(__WATCOM__) || defined(__GNU__)`. Then this can gradually be extended to other platforms for which the behaviour is well understood.

**Comment by mateuszviste** [comment]
> Do you want svarlang be portable to operating systems other than DOS, or keeping it DOS-only? That would heavily influence the things one can rely on.

DOS-only, definitely.

> Watcom reads its argv argument from the environment pointed to by the PSP.

Okay, so it does already the same thing that I came up with and copies the string in some DS-pointed buffer. No point duplicating this work then.

> For the start, I would use the __argv thing guarded by a `#if defined(__WATCOM__) || defined(__GNU__)`. Then this can gradually be extended to other platforms for which the behaviour is well understood.

Agreed, albeit at this point, since there is no "ideal" solution I think it's saner to delegate this problem to the application, and let it decide whether it wants to use _argv, argv[0], an environ pointer or anything else. I will update the code accordingly.

Thanks for your extensive research, it is very helpful.

Mateusz

**Comment by boeckmann** [comment]
> For the start, I would use the __argv thing guarded by a `#if defined(__WATCOM__) || defined(__GNU__)`. 

The above is certainly wrong, it is `#if defined( __WATCOMC__ ) || defined( __GNUC__ )`, with a C.

**Comment by mateuszviste** [comment]
About the header: \33 is a typo, it was meant to be \34, for the reason you mentioned. But once I noticed it I was already using SvarLANG in a few places so I did not want to change the format just for that. Now is the occasion to fix this.

num_languages: is it really useful? I feel like it is an artificial limitation.

Anyway, the idea is very sound and your work is very appreciated. Feel free to commit your changes to svarlang's trunk for both tlumacz and the lib, so the next release would use this new, better format.

On my side I will look into customizing the FOPEN/fopen thing with a compile-time flag so FDISK can use vanilla upstream again.

**Comment by boeckmann** [comment]
I finished implementing this via commit https://github.com/FDOS/fdisk/commit/609f3b582ec7e56a6dcbab63c355ec88838f29cf

Please have a look at it. If you are ok with it, I will integrate it to your SVN trunk, respecting the changes you did in the meantime. I tested it with the FDISK translations. Seems to work fine.

I slightly changed the file format:

- removed the language count, as you suggested
- pulled the version in front of \x1a and made it "1", so the header magic is "SvL1". This allows `type out.lng` show the exact file format version.

**Comment by boeckmann** [comment]
> This looks very good. Have you performed any kind of benchmark on this code to validate or assess the performance benefit? I do not doubt it is better, just wondering by how much.
Not now, but as a quick test started FDISK /? via DosBox with 8086 speed. The lag on page 3 is significiantly reduced (its the for loop iterating over non-existing strings that made the linear version slow).

But I want to do some profiling with wsample, wprof when time permits.

> Some loose remarks (that may or may not be valid, I didn't analyze the code in depth, just glanced):
>     • svarlang_dict[] is a linear table that holds interleaved values id,val,id,val. this requires to iterate the table two steps at a time when looking for something.
> wouldn't it be better to store the things in two separate tables? One table with ids and another one with values. This way it would be possible to avoid some *2 multiplications. Even if these are translated to shl ops in machine code it's still a few cycles saved here and there with no downsides.
I considered that also to be an option, but for debugging purposes decided against it. Now, with a hex editor, you can open the file, look for the id, and have the string offset right next to it without doing extra arithmetic. I found that useful while working on it. If you favour saving a few cycles I can change it.

>     • I think this might wrap around on edge-case values:
> fseek(fd, svarlang_string_count * 4 + buff16[1], SEEK_CUR);
> maybe safer to perform two fseek() operations. first to jump over dict, second one to jump over strings? or at least cast things to a long.
Yes, that might be a problem. Good idea! Will make two seeks of it.

>     • about the building of ordered dictionary: an alternative to the find-insertion-position algorithm could be to simply error out if translations are not ordered already in the text file. this would be actually a good validation, because it would help detect cases when the translator made mistakes in the ids because of bad copy/paste operations. so it would be (I think) a win-win.
I will add a warning but leave the position finding in. That doesn’t hurt :-)

>     • If I understand correctly it is impossible now to use a file that has a different amount of strings than the reference the program was compiled with. I am not sure this is an important regression, maybe not. Just stating that it exists.
Correct, at the moment this is fixed. I am also not sure about it. From my developer perspective I find it more convinient if this is catched. Makes it more likely that a mismatch between the program and the .lng file is catched.

For the moment,  I would leave it like this. If someone complains, this can be relaxed without changing the file format.

**Comment by mateuszviste** [comment]
This all sounds awesome, thanks! I am looking forward to see it land in the svn :-)

This new format could allow for an interesting feature in the future: finding duplicate strings and storing them once, as well as mapping partial matches. Like:

0.0:Changing the partition table
0.1:partition table
4.0:Changing the partition table

this could be optimized to keeping only the string "Changing the partition table", pointing both 0.0 and 4.0 to it and then pointing 0.1 to offset 13 of the same string.

In FDISK there are actually a few duplicated strings that would benefit from feature. Not that the savings would substantial, but still a nice idea for some future version.

**Comment by boeckmann** [comment]
I merged the current state to upstream and by accident changed the line endings for svarlang.c to CRLF. Sadly TortioseMerge did not show this as changes, therefore I did not notice till after commit.

**Comment by mateuszviste** [comment]
Thanks! CRLF is actually an improvement. I try to keep CRLF in all my DOS-related files, but sometimes I miss some. svarlang.c should have been CRLF since the begining, so it's a good thing you pushed it as your did. Thanks again!

**Comment by boeckmann** [comment]
In respect to FDISK I consider this finished and therefore close the issue. If further improvements to SvarLANG need to be made, that should go directly to upstream. From there I can import it to the FDISK repo.
