### ISSUE TITLE
Remove FDISKPT.INI support

### ISSUE THREAD

**Issue by boeckmann** [FDOS/fdisk#65]
Currently, if an FDISKPT.INI exists, (longer) partition type names are read from this file. However, these these descriptions can also be included directly in the source code, because the memory is reserved anyway as part of the data structures.

I think we should throw out support for it, and with it the code needed to parse this file.

**Comment by mateuszviste** [comment]
I always thought this fdiskpt file is for storing data that is too large to be kept in memory. But if it's in memory anyway, then indeed no point in keeping the file around.

I would go as far as suggest to drop support for the fdisk.ini file, I do not think this ini provides any practical value to users.

**Comment by boeckmann** [comment]
> I always thought this fdiskpt file is for storing data that is too large to be kept in memory.

Sadly not, it is loaded into this statically allocated array: https://github.com/FDOS/fdisk/blob/101e7ae9e1db1788d70539a0697d4b4b11f50925/source/fdisk/main.h#L169

FDISK is in many aspects a memory waster. There is also statically allocated space for eight disks (with 27 logical partitions).

**Comment by boeckmann** [comment]
fdiskpt.ini is gone. I put titles for the most common file system types in userint0.c. List may be extended, if anyone requests.

**Comment by mateuszviste** [comment]
FDISKPT.INI is still referenced in some translation strings. These strings are probably no longer referenced by FDISK and only take up RAM space. Which brings up another interesting need: it would be nice to have some automated way of detecting strings that are present in FDISK.LNG but never used. Sadly I do not see any easy way to achieve this reliably. A dumb approach would be to grep for the strings identifiers within lines that contain "svarlang_str...", but this will obviously fail in trickier situations where the strings's identifiers are built on the fly (like FDISK's help screen).

**Comment by boeckmann** [comment]
At least 7.2 is not used any longer. Did you notice other IDs? I will comment them out in the .TXT files.

**Comment by mateuszviste** [comment]
I was thinking about 7.2 and 7.3, but now I see that 7.3 is about something else. Hence no, at a quick glance with my feeble human eyes I do not see anything else than 7.2.

**Comment by boeckmann** [comment]
Ok, I see you already took care of removing 7.2 :-)
